<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>python21接口项目</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">python21接口项目</h1>
<p class='attribute'><strong>测试人员 : </strong> lsw</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-09-20 18:03:01</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:17.455313</p>
<p class='attribute'><strong>测试结果 : </strong> 共 17，通过 2，失败 15，通过率= 11.76%</p>

<p class='description'>python21项目实战</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 11.76% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 15 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 2 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 17 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>class21_test_api_webservice.testcases.test_bindbankcard.BankCardTestCase: 绑定银行卡接口</td>
    <td class="text-center">17</td>
    <td class="text-center">2</td>
    <td class="text-center">15</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',17)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_01: 正常绑定银行卡</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '0', 'retInfo': 'ok'} != {'retCode': 19001, 'retInfo': 银行卡号检验错误}
- {'retCode': '0', 'retInfo': 'ok'}
?             ^ ^             ^^^^

+ {'retCode': 19001, 'retInfo': 银行卡号检验错误}
?             ^^ ^^             ^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_02: 用户UID为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '用户ID错误'} != {'retCode': 19001, 'retInfo': 用户UID错误}
- {'retCode': '19001', 'retInfo': '用户ID错误'}
?             -     -             -      -

+ {'retCode': 19001, 'retInfo': 用户UID错误}
?                                 +



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_03: 用户UID不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '20042002', 'retInfo': '用户不存在'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '20042002', 'retInfo': '用户不存在'}
+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_04: 用户UID未进行实名认证</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '20042002', 'retInfo': '用户不存在'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '20042002', 'retInfo': '用户不存在'}
+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_case_bank_card_05: 支付密码为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_06: 支付密码错误</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '20042018', 'retInfo': '用户交易密码不正确或未配置'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '20042018', 'retInfo': '用户交易密码不正确或未配置'}
+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_case_bank_card_07: 绑定银行卡的手机号为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_08: 证件ID为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '支付密码错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '支付密码错误'}
?             -     -             ^^^^^  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_09: 证件ID错误</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 87, in setUp
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 83, in setUp
    self.assertEqual({"retCode": "0", "retInfo": "ok"}, response)
AssertionError: {'retCode': '0', 'retInfo': 'ok'} != {'retCode': 19001, 'retInfo': 身份证号检验错误}
- {'retCode': '0', 'retInfo': 'ok'}
?             ^ ^             ^^^^

+ {'retCode': 19001, 'retInfo': 身份证号检验错误}
?             ^^ ^^             ^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_10: 证件ID与实名认证中的不一致</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '20042006', 'retInfo': '用户实名信息比对错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '20042006', 'retInfo': '用户实名信息比对错误'}
+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_11' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_11: 持卡人姓名为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_11'>失败</button>
    <div id='div_ft1_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_11'>失败</button>
    <div id='div_ft1_11' class="collapse in" align="left">
    <pre>
    
ft1_11: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '持卡人姓名错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '持卡人姓名错误'}
?             -     -             ^^ ^^^  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^^^ ^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_12' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_12: 持卡人姓名与实名认证中的不一致</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse in" align="left">
    <pre>
    
ft1_12: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '20042006', 'retInfo': '用户实名信息比对错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '20042006', 'retInfo': '用户实名信息比对错误'}
+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_13' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_13: 卡号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_13'>失败</button>
    <div id='div_ft1_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_13'>失败</button>
    <div id='div_ft1_13' class="collapse in" align="left">
    <pre>
    
ft1_13: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '卡号错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '卡号错误'}
?             -     -             ^    -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^^^ ++



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_14' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_14: 银行类型为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse in" align="left">
    <pre>
    
ft1_14: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '银行类型错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '银行类型错误'}
?             -     -             ^  ^^  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^  ^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_15' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_15: 银行名称/开户行名称为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_15'>失败</button>
    <div id='div_ft1_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_15'>失败</button>
    <div id='div_ft1_15' class="collapse in" align="left">
    <pre>
    
ft1_15: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '银行卡号检验错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '银行卡号检验错误'}
?             -     -             ^    --  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^   ++



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_16' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_16: 开户地区，省级为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse in" align="left">
    <pre>
    
ft1_16: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '银行卡号检验错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '银行卡号检验错误'}
?             -     -             ^    --  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^   ++



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_17' class='none'>
    <td class='failCase'><div class='testcase'>test_case_bank_card_17: 开户城市为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_17'>失败</button>
    <div id='div_ft1_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_17'>失败</button>
    <div id='div_ft1_17' class="collapse in" align="left">
    <pre>
    
ft1_17: Traceback (most recent call last):
  File "D:\class21\class21_test_api_webservice\pack_lib\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 114, in test_case_bank_card
    raise e
  File "D:\class21\class21_test_api_webservice\testcases\test_bindbankcard.py", line 104, in test_case_bank_card
    self.assertEqual(eval(case.excepted), response)
AssertionError: {'retCode': '19001', 'retInfo': '银行卡号检验错误'} != {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
- {'retCode': '19001', 'retInfo': '银行卡号检验错误'}
?             -     -             ^    --  -

+ {'retCode': 19001, 'retInfo': 绑定的银行卡手机号错误}
?                               ^^^   ++



    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>17</td>
    <td>2</td>
    <td>15</td>
    <td>0</td>
    <td>通过率：11.76%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
